version: "3.6"

services:
  scrapyd:
    image: scrapyd
    build: .
    env_file: .env
    ports:
      - "6800:6800"
    configs:
      - source: scrapy.cfg
        target: /usr/src/scrapy.cfg
      - source: scrapyd.conf
        target: /usr/src/scrapyd.conf
    volumes:
      - "./app:/usr/src/app"
      - "./data:/usr/src/data"
      - "./logs:/usr/src/logs"
      - "./scrapy.cfg:/usr/src/scrapy.cfg"
      - "./scrapyd.conf:/usr/src/scrapyd.conf"
      - "./setup.py:/usr/src/setup.py"
    command: scrapyd

configs:
  scrapy.cfg:
    file: ./scrapy.cfg
  scrapyd.conf:
    file: ./scrapyd.conf

volumes:
  app:
  data:
  logs:
